/*********************************************************************************/
/* Author    : Ahmed Osama                                                       */
/* Version   : V01                                                               */
/* Date      : 02 OCT  2022                                                      */
/*********************************************************************************/

#ifndef	 	HIR_CONFIG_H
#define 	HIR_CONFIG_H

volatile u8 u8RemoteControlData=0;

#endif
