/*********************************************************************************/
/* Author    : Ahmed Osama                                                       */
/* Version   : V01                                                               */
/* Date      : 02 OCT  2022                                                      */
/*********************************************************************************/

#ifndef	 	HIR_PRIVATE_H
#define 	HIR_PRIVATE_H

static void VoidTakeAction(void);
static void VoidPlay(void);


#endif
