/*********************************************************************************/
/* Author    : Ahmed Osama                                                       */
/* Version   : V01                                                               */
/* Date      : 02 OCT  2022                                                      */
/*********************************************************************************/

#ifndef	 	HIR_INTERFACE_H
#define 	HIR_INTERFACE_H

void voidGetFrame_TakeAction_Play(void);




#endif
